// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package model

import (
	"database/sql"
)

type Time struct {
	ID     int64
	UserID int64
	Time   int64
	Type   string
}

type User struct {
	ID   int64
	Name sql.NullString
}
